server:
  port: ${PORT:5001}

base-url: /api
rollbar_token: ${ROLLBAR_TOKEN:b2a13ba384d241da822552c54ccf3b95}

spring:
  application:
    name: taskManager

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop

springdoc:
  api-docs:
    path: /swagger.html